# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Deno environment
      uses: denolib/setup-deno@v1.3.0
      with:
        # Version range or exact version of a Deno version to use.
        deno-version: v0.x # optional, default is v0.x

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        deno run --unstable --allow-net --allow-read --allow-write index.ts

    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
  
